api:
  insecure: true

providers:
  docker: { }

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

certificatesResolvers:
  le-resolver:
    acme:
      email: '{{ env "LETSENCRYPT_EMAIL" | default "test@test.com" }}'
      storage: acme.json
      httpChallenge:
        entryPoint: web
